[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
    "npm ci --include=dev",
    "cd client && npm ci",
    "cd server && npm ci"
]

[phases.build]
cmds = [
    "cd client && npm run type-check || echo 'TypeScript check failed, continuing...'",
    "cd client && npm run build"
]

[start]
cmd = "cd server && npm start"

[variables]
NODE_ENV = "production"
PORT = "5001"
NIXPACKS_PATH = "/nix/var/nix/profiles/default/bin"
